##---
# Source: olm/templates/01-alm-operator.serviceaccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: alm-operator-serviceaccount
  namespace: kube-system
  labels:
    tectonic-operators.coreos.com/managed-by: tectonic-x-operator
imagePullSecrets:
- name: coreos-pull-secret
