apiVersion: v2
description: A Helm chart for Kubernetes
name: olm
version: 0.0.0-dev
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
