---
# Source: olm/templates/0000_50_olm_12-olm-operators.catalogsource.yaml
#! validate-crd: ./deploy/chart/templates/06-catalogsource.crd.yaml
#! parse-kind: CatalogSource
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: olm-operators
  namespace: olm
spec:
  sourceType: internal
  configMap: olm-operators
  displayName: OLM Operators
  publisher: Red Hat
