apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operator-lifecycle-manager
  labels:
    pod-security.kubernetes.io/enforce: restricted
    openshift.io/scc: "restricted-v2"
    openshift.io/cluster-monitoring: "true"
  annotations:
    openshift.io/node-selector: ""
    workload.openshift.io/allowed: "management"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators
  labels:
    pod-security.kubernetes.io/enforce: restricted
    openshift.io/scc: "restricted-v2"
  annotations:
    openshift.io/node-selector: ""
    workload.openshift.io/allowed: "management"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
