apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: olm-alert-rules
  namespace: openshift-operator-lifecycle-manager
  labels:
    prometheus: alert-rules
    role: alert-rules
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  groups:
    - name: olm.csv_abnormal.rules
      rules:
        - alert: CsvAbnormalFailedOver2Min
          expr: csv_abnormal{phase=~"^Failed$"}
          for: 2m
          labels:
            severity: warning
            namespace: "{{ $labels.namespace }}"
          annotations:
            summary: CSV failed for over 2 minutes
            description: Fires whenever a CSV has been in the failed phase for more than 2 minutes.
            message: Failed to install Operator {{ $labels.name }} version {{ $labels.version }}. Reason-{{ $labels.reason }}
        - alert: CsvAbnormalOver30Min
          expr: csv_abnormal{phase=~"(^Replacing$|^Pending$|^Deleting$|^Unknown$)"}
          for: 30m
          labels:
            severity: warning
            namespace: "{{ $labels.namespace }}"
          annotations:
            summary: CSV abnormal for over 30 minutes
            description: Fires whenever a CSV is in the Replacing, Pending, Deleting, or Unkown phase for more than 30 minutes.
            message: Failed to install Operator {{ $labels.name }} version {{ $labels.version }}. Phase-{{ $labels.phase }} Reason-{{ $labels.reason }}
    - name: olm.installplan.rules
      rules:
        - alert: InstallPlanStepAppliedWithWarnings
          expr: sum(increase(installplan_warnings_total[5m])) > 0
          labels:
            severity: warning
          annotations:
            summary: API returned a warning when modifying an operator
            description: Fires whenever the API server returns a warning when attempting to modify an operator.
            message: The API server returned a warning during installation or upgrade of an operator. An Event with reason "AppliedWithWarnings" has been created with complete details, including a reference to the InstallPlan step that generated the warning.
