apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: olm-alert-rules
  namespace: openshift-operator-lifecycle-manager
  labels:
    prometheus: alert-rules
    role: alert-rules
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  groups:
    - name: olm.csv_abnormal.rules
      rules:
        - alert: CsvAbnormalFailedOver2Min
          expr: csv_abnormal{phase=~"^Failed$"}
          for: 2m
          labels:
            severity: warning
            namespace: "{{ $labels.namespace }}"
          annotations:
            message: Failed to install Operator {{ $labels.name }} version {{ $labels.version }}. Reason-{{ $labels.reason }}
        - alert: CsvAbnormalOver30Min
          expr: csv_abnormal{phase=~"(^Replacing$|^Pending$|^Deleting$|^Unknown$)"}
          for: 30m
          labels:
            severity: warning
            namespace: "{{ $labels.namespace }}"
          annotations:
            message: Failed to install Operator {{ $labels.name }} version {{ $labels.version }}. Phase-{{ $labels.phase }} Reason-{{ $labels.reason }}
