apiVersion: v1
kind: Service
metadata:
  name: packageserver
  labels:
    app: packageserver
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: "packageserver-serving-cert"
spec:
  ports:
  - port: 5443
    protocol: TCP
    targetPort: 5443
  selector:
    app: packageserver
  type: ClusterIP
