blank_issues_enabled: false
contact_links:
  - name: OLM Kubernetes Slack Channel
    url: https://kubernetes.slack.com/archives/C0181L6JYQ2
    about: Join the "#olm-dev" channel on the kubernetes slack - it's a good place to ask OLM-related questions!
  - name: OLM Working Group Meeting
    url: https://docs.google.com/document/d/1Zuv-BoNFSwj10_zXPfaS9LWUQUCak2c8l48d0-AhpBw/edit?usp=sharing
    about: The OLM working group meeting is a great place to bring up feature requests and broader community topics. 
