##---
# Source: olm/templates/22-packageserver.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.packages.apps.redhat.com
spec:
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQWQyZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFjTVJvd0dBWURWUVFERXhGd1lXTnIKWVdkbExYTmxjblpsY2kxallUQWVGdzB4T0RBNU1Ua3hOVEk1TWpGYUZ3MHhPVEE1TVRreE5USTVNakZhTUJ3eApHakFZQmdOVkJBTVRFWEJoWTJ0aFoyVXRjMlZ5ZG1WeUxXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUF5Sko5amhubXdaaEV2enRZQlNicWt0MTFBUWF3cWNldks2ZS9aY0VnQ0l6RHQvYWkKNVdjdjd2eWE5NlFSZkVZWG5qN2t0VnY3MzYrZGVraWFodWswK0taOXNnTmpIcXp0eGpZUVZvSHI1NTdLTW4vOApxOUd4QUVtQWgvWkdqUzM5bkNtaW5YSUN1M3I2bUdtK2pzQTA2VTAzWUtXclRtVlQweThBbys0MnM2RGRKTXZ5ClVmSjMvT0pLSzFxQVAyQS90ckRieG5peVUyRnBIWVpzVlRWdDM3RU1VYW9VTjJLeldSSVlpODlZM05HYVNxMVYKbzdaeWI2WEY2Uyt3dUpybUZMek9VYTByQ1o2Mko0ajg3OVl2Q0lvODVKQTNWaHdpT3hlYmQ4U2Q0ZW10Z0F3NwpHUm9vWkVraFhLVjBzT2pLdnBvamtSQmlTc0xZUVZ3VTJHTFpKUUlEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFCkJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUYKTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSytpcXlUM1NUenM0OHVyTTM1bFBFZWpYVll4TWNHbApnYnExOGt5NG1UQ1lIaFlleDQ2ZVltK1dQMFBCVU43ZHZiNDNhNlA5d0lmZURQem15SjNKOEF1TUxEeVRGSUErClk1Q1M4TlFzOVpzdi9IN0MvVU9HaTFjQzVOVCt5eWU4WXB3cnpLVmphMXNVNFZXN1dUWS9xVnhmUFVKQjNhS3QKcnhzWTU4Vmd6SE91ajRlNE92UCt4TTJEcjJEa2pXSkw4aml4bmdnL0Z6MTU5ZHQvNlhuSko2ZDZHZ3o2cVFDVQpGRkZEQjhTMEozVWRDSUs5cjNwQVh4eFZubVhGRGhaRVZGeFRkcVE4VTNtTmdkRjlqaVVtams2VkdhSHJKMkc5Cmd4c0JMeTJCS050NzBHWmZYTC9ySGY5cWtVN1dpcmlaVHpzNitqb1ZEWnBOMmYzSzZjd2xKa009Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  group: packages.apps.redhat.com
  groupPriorityMinimum: 2000
  versionPriority: 15
  service:
    name: package-server
    namespace: kube-system
  version: v1alpha1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packagemanifest:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: packagemanifest-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packagemanifest-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: package-apiserver-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregated-apiserver-clusterrole
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: kube-system
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: package-server-certs
  namespace: kube-system
  labels:
    app: package-server
data:
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPRENDQWlDZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFjTVJvd0dBWURWUVFERXhGd1lXTnIKWVdkbExYTmxjblpsY2kxallUQWVGdzB4T0RBNU1Ua3hOVEk1TWpKYUZ3MHhPVEE1TVRreE5USTVNakphTUJreApGekFWQmdOVkJBTVREbkJoWTJ0aFoyVXRjMlZ5ZG1WeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQXpiQnNZL3hjeWc0bXlTWlR5OWVRNXpYU0JlWjFjTlVYVXp6TEIvQjFUUkJMYjlUR1I4Z1YKZGNmQ09YeElGRlRuVHd6NnRlTlZZczRLclNLc3V6eFFCQko4aUVKMDhTanZqQTFwcXNUWE9OemtDVHVlYUs4ZQp2WGs0SVBvUmJ2NWgyQklVazZBaGVxa0xJVE1TV0ViT3dDY3dIc3lpQ0p5dDlzTkxDSUpsY3RXOUgrbmdMSEZ5ClI2ai9Qck9kUmVoL21NRkF2YTVKbGNONHRFT2dxdFFjNndqWXRxMVJzSkxzRlErc2V4VTFhUWthQjZwVFFJK1IKclc2TFU4dU1CbkJmOWZoTUZUdjdCMDNvajdyLyt4V1JKWjFpdFIyeEpRckhkSnkrc1YydmpqNGg5dHNDc3RkUwpxTmdYNHA1RVNQRDNLZzRHSkJYejQ3MG1IN1N1N3BxTXNRSURBUUFCbzRHSE1JR0VNQTRHQTFVZER3RUIvd1FFCkF3SUZvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXcKQURCRkJnTlZIUkVFUGpBOGdocHdZV05yWVdkbExYTmxjblpsY2k1cmRXSmxMWE41YzNSbGJZSWVjR0ZqYTJGbgpaUzF6WlhKMlpYSXVhM1ZpWlMxemVYTjBaVzB1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRREJDRWxsClNCZlhhZUQ3SWh6WHlSaXk3Y0FwTStJVmNWOURTWmE4Vm1wc1hydFhJMUJVelN3aFQwbjhmRlZiY3l2OFpzTnEKdVgrRGQ0eWR5TWV0ZUVpS3VhMmZpVXIvaDU0YmpTa0ZsbzZRaW1xN3pLbFB2b1IrZWRLM3ArVFJnZzdELzdGUgp5WDVZeGx5amJPUy9KVHQxMC91aVVxLzZqbjZBOURVSkJ2QWJuR3JzRzY1UkxLdGZuTzNLc2duYUpVN2s5Mm1lCjYyT3gzMGlsQ3pqSW5jQW0rZ09rRFNlNmhUdThuRjVXNjJiRWlMeG43NSt4bk9vazgrbkhtTmNEMzVWU0pqRXUKemJKNVpoZVA1NmFPUGFKYU1iYlV0WDBHamltellncllUd2pQN3pGMStubE13ZTJOODFDeWNnc0srUk5NME4rKwpwdEFja0ZlQkNwYkRjdFVECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  tls.key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBemJCc1kveGN5ZzRteVNaVHk5ZVE1elhTQmVaMWNOVVhVenpMQi9CMVRSQkxiOVRHClI4Z1ZkY2ZDT1h4SUZGVG5Ud3o2dGVOVllzNEtyU0tzdXp4UUJCSjhpRUowOFNqdmpBMXBxc1RYT056a0NUdWUKYUs4ZXZYazRJUG9SYnY1aDJCSVVrNkFoZXFrTElUTVNXRWJPd0Njd0hzeWlDSnl0OXNOTENJSmxjdFc5SCtuZwpMSEZ5UjZqL1ByT2RSZWgvbU1GQXZhNUpsY040dEVPZ3F0UWM2d2pZdHExUnNKTHNGUStzZXhVMWFRa2FCNnBUClFJK1JyVzZMVTh1TUJuQmY5ZmhNRlR2N0IwM29qN3IvK3hXUkpaMWl0UjJ4SlFySGRKeStzVjJ2amo0aDl0c0MKc3RkU3FOZ1g0cDVFU1BEM0tnNEdKQlh6NDcwbUg3U3U3cHFNc1FJREFRQUJBb0lCQURyQmwrVGo5Um1lKzBOZwptSFZWU2NaU1lJRmcrTkZYZmNkQVNYc21IRXY4U0tCVWRxT1FxMWl1ekhPaFpmR3c0elo0cmJHQmxDV2FXQUJuCk5GSjBBeU4ycUc1QUZhbkNHTk80RFNSRUFIcjAxb3N3cGFxZnc3YzZSbWRkSjllK0FQTTVEdm13dDMrVGhHTmkKZEc0VkpBQk44WGdLMm9wOVAxQ0xMd2JxUU5LUmFzc2prd1ZjeG45T3h3ZXl6d0Ivd1dSOVBSRjdpODZKTVRPVwpTQXVHbTNKUUQ4RHp5eUZwcGE5QkpWTWR4V211dnRuKzBVallFbkFodHJwZVRYYVJVVHNVWjRHbUxKYkhvaXlkCmVxR0R2dFpDSWVEQk5oTk5TT2YxSXFVOWRqQWsxdjBZVlJzQmZQWVoreUtZaDlKTzIxWHM0YndCblc5bk1wSWoKa3lyeTYrVUNnWUVBNFhzQjF2cklOR3JvZE1SS25sek1GUlNCZ24xMXVIek1ZSnRpVklYemg2cTNwN2VUQnBRdApFYktER0lYU25Td1lxaVZJRHJlOUdTUXdPRi9QMG84QTFDbjhiQnhBN1pRSWI2b3gwUWhJUEV1VW04VGY0Sm1MCmJwMmFkcG9uMDdxZks3ZHF5bEJKVVl2OGpRc1dKSWhxVG81dkxCRzBhZjZEQlRrR2VKSlRxNThDZ1lFQTZZZWoKVWNkdFJHeklIS3BoNXh6ZlN1bFplSTVMT243ekU5SHhwTHJnbjltZFpmd2tPODV0MHU4SGgrOUJkMVMraTVRawptd3M3RnloR2p0aWV5QVNadFErYjlEeklleVhKNlFZai9TVmtmQUJ1d25EcXlSWFdWMXdXb25sUFJoR3daU0tVCnIvYTFxU24vNHNuT243dlhEa2ZaQUJvaE1iVmJrNkFhd1pZOTVhOENnWUVBaDdOU0RpSHI3N0FQcW9hZ0tlTEwKYUR4cEhUR0ljYm1aL3VKRk1YMVViV2ZQRS84bFd5WStZWkkvMTdoaVl2a3c5dVZ0RW41K0xlMWJuL0g1ejAwRgpRS3JzSWR4M0x3U1NkekhFdlhyd2pta21UUUVWZzhTazU3T3VUSWJHUldUaGVwdnVoMGYrZURkNWpTRUkrSCtwCkN4SXAwaW50bklUeU1XaDZmb0lDSFIwQ2dZRUEzT01jR3MwOFVEMW9wcHlPa0JFaUwvUTZXYXFXQTVWeWpHdkgKV2Q0ZGUzVlZ5TkpPMzNicE1GeEJUbFdESWNFNW5rS1l3VUpGT1NreVhBa1BYdmZpLzN6dE1YNlF6dEsyZ2IvNgpLSWJHM2ZkMnpGb0w2Zm5Lek1UZzcvczRmWGxiMUwxNTBGcldCMVVmb1Q3clB2Rm9nQ3g3Vi9wZkxXcHlYVmRTCkY0dnByaWNDZ1lCNVdzMHdHMUIxUm9jdFZYMnZMZk1ON0ROUXU4ampRd1FUTW5ucWtkbVd1OUhzeG42aVM0d24KSmlwV1ZDQXlML0V1RTVyZlFyZkl2cFRCdVQ2T2xIUHYrdnBCRzJGODdlK2FyUGJvWFhVMmd3MEpPSnVTL2kvVAp4cjRVRW5RQndFUHRmb0R0V3IrbTVWdXZQTXBQQjFlTC9QK3FrK1BvV0JLOG9vcnZmVWtwcXc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: package-server
  namespace: kube-system
  labels:
    app: package-server
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: package-server
  template:
    metadata:
      labels:
        app: package-server
    spec:
      serviceAccountName: olm-operator-serviceaccount
      containers:
      - name: package-server
        command:
        - /bin/package-server
        - -v=4
        - --debug
        image: quay.io/coreos/package-server@sha256:66513e76ac0443b6ecec3138a88fa6850a98b1db95400f2f83f6012bee693c6f
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        volumeMounts:
        - name: certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 443
        readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 443
      volumes:
      - name: certs
        secret:
          secretName: package-server-certs
          items:
          - key: tls.crt
            path: apiserver.crt
          - key: tls.key
            path: apiserver.key
      imagePullSecrets:
        - name: coreos-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: package-server
  namespace: kube-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: package-server
