name: flake-analyzer-periodics
on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  generate-flake-analysis-report:
    runs-on: ubuntu-latest
    steps:
      - name: Periodic Flake Report
        env:
          OWNER: operator-framework
          REPO: operator-lifecycle-manager
          TEST_SUITE: e2e-test-output
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone -b v0.1.2 https://github.com/operator-framework/flake-analyzer.git
          cd ./flake-analyzer
          make report-today  OUTPUT_FILE=./report/artifacts/flake-report-today-$(date +"%m-%d-%Y").yaml
          make report-last-7-days OUTPUT_FILE=./report/artifacts/flake-report-last-7-days-$(date +"%m-%d-%Y").yaml
          make report-prev-7-days OUTPUT_FILE=./report/artifacts/flake-report-prev-7-days-$(date +"%m-%d-%Y").yaml
      - name: Archive Reoport artifacts # test results are only uploaded if any of the e2e tests fails
        uses: actions/upload-artifact@v2
        with:
          name: flake-report-${{ github.run_id }}
          path: ${{ github.workspace }}/flake-analyzer/report/artifacts/*
