{{- define "packageserver.clusterserviceversion" -}}
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: packageserver
  namespace: {{ .Values.namespace }}
  {{- if and .Values.installType (eq .Values.installType "ocp") }}
  {{- /*
  This annotation injection is a workaround for BZ-1950047, since the associate
  annotation in _packageserver.deployment-spec.yaml is presently ignored.
  */}}
  annotations:
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
  {{- end }}
  labels:
    olm.version: {{ .Chart.Version }}
    {{- if .Values.writePackageServerStatusName }}
    olm.clusteroperator.name: {{ .Values.writePackageServerStatusName }}
    {{- end }}
spec:
  displayName: Package Server
  description: Represents an Operator package that is available from a given CatalogSource which will resolve to a ClusterServiceVersion.
  minKubeVersion: {{ .Values.minKubeVersion }}
  keywords: ['packagemanifests', 'olm', 'packages']
  maintainers:
  - name: Red Hat
    email: openshift-operators@redhat.com
  provider:
    name: Red Hat
  cleanup:
    enabled: false
  customresourcedefinitions: {}
  links:
  - name: Package Server
    url: https://github.com/operator-framework/operator-lifecycle-manager/tree/master/pkg/package-server
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: true
  - type: AllNamespaces
    supported: true
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: olm-operator-serviceaccount
        rules:
        - apiGroups:
            - authorization.k8s.io
          resources:
            - subjectaccessreviews
          verbs:
            - create
            - get
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - "operators.coreos.com"
          resources:
          - catalogsources
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - "packages.operators.coreos.com"
          resources:
          - packagemanifests
          verbs:
          - get
          - list
      deployments:
      - name: packageserver
        {{- include "packageserver.deployment-spec" . | nindent 8 }}
  maturity: alpha
  version: {{ .Chart.Version }}
  apiservicedefinitions:
    owned:
    - group: packages.operators.coreos.com
      version: v1
      kind: PackageManifest
      name: packagemanifests
      displayName: PackageManifest
      description: A PackageManifest is a resource generated from existing CatalogSources and their ConfigMaps
      deploymentName: packageserver
      containerPort: {{ .Values.package.service.internalPort }}
{{- end -}}
