- command: update
  path: spec.template.metadata.annotations."target.workload.openshift.io/management"
  value: '{"effect": "PreferredDuringScheduling"}'
- command: update
  path: spec.template.spec.priorityClassName
  value: system-cluster-critical
- command: update
  path: spec.template.spec.containers[*].env[+]
  value:
    name: RELEASE_VERSION
    value: "0.0.1-snapshot"
