apiVersion: v1
kind: ServiceAccount
metadata:
  name: lifecycle-controller
  namespace: openshift-operator-lifecycle-manager
  annotations:
    release.openshift.io/feature-set: "TechPreviewNoUpgrade"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    capability.openshift.io/name: "OperatorLifecycleManager"
    include.release.openshift.io/hypershift: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-lifecycle-manager-lifecycle-controller
  annotations:
    release.openshift.io/feature-set: "TechPreviewNoUpgrade"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    capability.openshift.io/name: "OperatorLifecycleManager"
    include.release.openshift.io/hypershift: "true"
rules:
  # Read APIServer for TLS security profile configuration
  - apiGroups: ["config.openshift.io"]
    resources: ["apiservers"]
    verbs: ["get", "list", "watch"]
  # Watch CatalogSources cluster-wide
  - apiGroups: ["operators.coreos.com"]
    resources: ["catalogsources"]
    verbs: ["get", "list", "watch"]
  # Watch catalog pods cluster-wide
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  # Manage lifecycle-server deployments
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Manage lifecycle-server services
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Manage lifecycle-server serviceaccounts
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Manage lifecycle-server networkpolicies
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Manage lifecycle-server clusterrolebindings
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Required to grant these permissions to lifecycle-server via CRB
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
  # Leader election
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-lifecycle-manager-lifecycle-controller
  annotations:
    release.openshift.io/feature-set: "TechPreviewNoUpgrade"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    capability.openshift.io/name: "OperatorLifecycleManager"
    include.release.openshift.io/hypershift: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-lifecycle-manager-lifecycle-controller
subjects:
  - kind: ServiceAccount
    name: lifecycle-controller
    namespace: openshift-operator-lifecycle-manager
