apiVersion: v1
kind: Service
metadata:
  name: olm-operator-metrics
  namespace: openshift-operator-lifecycle-manager
  labels:
    app: olm-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    capability.openshift.io/name: "OperatorLifecycleManager"
    include.release.openshift.io/hypershift: "true"
spec:
  type: ClusterIP
  ports:
    - name: https-metrics
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: olm-operator
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-operator-metrics
  namespace: openshift-operator-lifecycle-manager
  labels:
    app: catalog-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    capability.openshift.io/name: "OperatorLifecycleManager"
    include.release.openshift.io/hypershift: "true"
spec:
  type: ClusterIP
  ports:
    - name: https-metrics
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: catalog-operator
