---
# Source: olm/templates/0000_50_olm_16-packageserver.deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: packageserver
  namespace: openshift-operator-lifecycle-manager
  labels:
    app: packageserver
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: packageserver
  template:
    metadata:
      labels:
        app: packageserver
    spec:
      serviceAccountName: packageserver
      nodeSelector:
                  beta.kubernetes.io/os: linux
                  node-role.kubernetes.io/master: ""
                  
      tolerations:
                  - operator: Exists
                  
      containers:
      - name: packageserver
        command:
        - /bin/package-server
        - -v=4
        - --secure-port
        - "5443"
        - --global-namespace
        - openshift-operator-lifecycle-manager
        image: quay.io/operator-framework/olm@sha256:4b7dec341fc754fdd2c8784ca7d81747ebbb2b87866b9e61ebbebc8c5614cfdc
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5443
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 5443
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 5443

