---
# Source: olm/templates/0000_50_olm_00-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operator-lifecycle-manager
  labels:
    openshift.io/run-level: "1"
  annotations:
    openshift.io/node-selector: ""
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators
  labels:
    openshift.io/run-level: "1"
  annotations:
    openshift.io/node-selector: ""
