- command: update
  path: spec.template.metadata.annotations
  value:
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    openshift.io/required-scc: restricted-v2
- command: update
  path: spec.template.spec.priorityClassName
  value: system-cluster-critical
- command: update
  path: spec.template.spec.containers[*].env[+]
  value:
    name: RELEASE_VERSION
    value: "0.0.1-snapshot"
- command: update
  path: spec.template.spec.containers[0].args[+]
  value:
    --protectedCopiedCSVNamespaces
- command: update
  path: spec.template.spec.containers[0].args[+]
  value:
    openshift
- command: update
  path: spec.template.spec.containers[*].securityContext
  value:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]
- command: update
  path: spec.template.spec.securityContext
  value:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
- command: update
  path: spec.template.spec.containers[0].livenessProbe.httpGet.port
  value: 8443
- command: update
  path: spec.template.spec.containers[0].livenessProbe.httpGet.scheme
  value: HTTPS
- command: update
  path: spec.template.spec.containers[0].readinessProbe.httpGet.port
  value: 8443
- command: update
  path: spec.template.spec.containers[0].readinessProbe.httpGet.scheme
  value: HTTPS
- command: update
  path: spec.template.spec.containers[0].ports[0].containerPort
  value: 8443
- command: update
  path: spec.template.spec.volumes[+]
  value:
    name: olm-operator-serving-cert
    secret:
      secretName: olm-operator-serving-cert
- command: update
  path: spec.template.spec.containers[+]
  value:
    args:
      - --secure-listen-address=0.0.0.0:9443
      - --upstream=https://127.0.0.1:8443/
      - --tls-cert-file=/etc/tls/private/tls.crt
      - --tls-private-key-file=/etc/tls/private/tls.key
      - --upstream-ca-file=/srv-cert/tls.crt
      - --logtostderr=true
    image: quay.io/openshift/origin-kube-rbac-proxy:latest
    imagePullPolicy: IfNotPresent
    name: kube-rbac-proxy
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]
    ports:
      - containerPort: 9443
        name: metrics
        protocol: TCP
    resources:
      requests:
        memory: 20Mi
        cpu: 10m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
      - mountPath: /etc/tls/private
        name: olm-operator-serving-cert
      - mountPath: /srv-cert
        name: srv-cert
        readOnly: true
